version: 3
includes:
  root: ../Taskfile.yaml
tasks:
  pydantic-to-typescript:
    cmd: poetry run pydantic2ts --module ./src/api/model.py --output ../frontend/src/types/api.d.ts

  make-wled-models:
    cmd: poetry run datamodel-codegen --input ../share/schema/wled_state_schema.json --input-file-type jsonschema --output ./src/lib/model/wled.py --output-model-type pydantic_v2.BaseModel

  make-led-sequence-schema:
    cmds:
      - poetry run python ./bin/py/dump_led_sequence.py
      - cp ../share/schema/led_sequence_schema.json ../frontend/src/schema.json

  run-server:
    cmd: poetry run uvicorn api.main:app --port 8080 --reload --log-config logging.yaml