# /etc/mosquitto/mosquitto.conf

# Listen on all network interfaces, default MQTT port
listener 1883
allow_anonymous true

# Optional: disable persistence for simplicity
persistence false
max_keepalive 0
