"""add playlist

Revision ID: 1104c70dcaed
Revises: 93973b82f9c9
Create Date: 2026-01-03 02:48:20.883653

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from api.orm import SqliteUuid

# revision identifiers, used by Alembic.
revision: str = "1104c70dcaed"
down_revision: Union[str, Sequence[str], None] = "93973b82f9c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlist",
        sa.Column("id", SqliteUuid(), nullable=False),
        sa.Column("host_id", SqliteUuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("shuffle", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["wled_host.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "playlist_entry",
        sa.Column("id", SqliteUuid(), nullable=False),
        sa.Column("playlist_id", SqliteUuid(), nullable=False),
        sa.Column("sequence_id", SqliteUuid(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlist.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sequence_id"],
            ["sequence.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("playlist_entry")
    op.drop_table("playlist")
    # ### end Alembic commands ###
