"""Add segment sets

Revision ID: 314e03cb6558
Revises: 863d68aa14f4
Create Date: 2026-02-13 19:19:19.283464

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text

from api.orm import PostgresSegments

# revision identifiers, used by Alembic.
revision: str = "314e03cb6558"
down_revision: Union[str, Sequence[str], None] = "863d68aa14f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "segment_set",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("host_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("segments", PostgresSegments(astext_type=Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["wled_host.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("segment_set")
    # ### end Alembic commands ###
