"""add sequence_id to sequence

Revision ID: 794e343c3ae2
Revises: 314e03cb6558
Create Date: 2026-02-14 01:43:55.303953

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import select
from sqlalchemy.orm import sessionmaker

from api.orm import SequenceOrm as SequenceOrm

# revision identifiers, used by Alembic.
revision: str = "794e343c3ae2"
down_revision: Union[str, Sequence[str], None] = "314e03cb6558"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sequence", sa.Column("segment_set_id", sa.UUID(), nullable=True))
    session = sessionmaker(bind=op.get_bind())()
    for sequence in session.execute(select(SequenceOrm)).scalars():
        sequence.segment_set_id = sequence.host.segment_sets[0].id
        session.add(sequence)

    session.flush()
    op.alter_column(
        "sequence", "segment_set_id", nullable=False, existing_type=sa.UUID()
    )
    op.create_foreign_key(None, "sequence", "segment_set", ["segment_set_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sequence", type_="foreignkey")
    op.drop_column("sequence", "segment_set_id")
    # ### end Alembic commands ###
