"""Add playlist repeat

Revision ID: 863d68aa14f4
Revises: 6b0fce7ef33f
Create Date: 2026-01-26 23:54:01.347929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '863d68aa14f4'
down_revision: Union[str, Sequence[str], None] = '6b0fce7ef33f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist', sa.Column('repeat', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist', 'repeat')
    # ### end Alembic commands ###
