"""init

Revision ID: 93973b82f9c9
Revises:
Create Date: 2025-10-22 13:49:19.329922

"""

from typing import Sequence, Union
from uuid import UUID

import sqlalchemy as sa
from alembic import op
from sqlalchemy import TEXT, Dialect, TypeDecorator

from api.orm import PostgresLedSequence


class SqliteUuid(TypeDecorator):
    impl = TEXT
    cache_ok = True

    def process_bind_param(self, value: UUID, dialect: Dialect):
        if value is not None:
            return str(value)
        return value

    def process_result_value(self, value: str, dialect: Dialect):
        if value is not None:
            return UUID(value)
        return value

    def python_type(self):
        return UUID


# revision identifiers, used by Alembic.
revision: str = "93973b82f9c9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wled_host",
        sa.Column("id", SqliteUuid(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sequence",
        sa.Column("id", SqliteUuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("host_id", SqliteUuid(), nullable=False),
        sa.Column("sequence", PostgresLedSequence(), nullable=False),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["wled_host.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sequence")
    op.drop_table("wled_host")
    # ### end Alembic commands ###
