"""init

Revision ID: 93973b82f9c9
Revises: 
Create Date: 2025-10-22 13:49:19.329922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from api.orm import SqliteUuid, SqliteLedSequence

# revision identifiers, used by Alembic.
revision: str = '93973b82f9c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wled_host',
    sa.Column('id', SqliteUuid(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sequence',
    sa.Column('id', SqliteUuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('host_id', SqliteUuid(), nullable=False),
    sa.Column('sequence', SqliteLedSequence(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['wled_host.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sequence')
    op.drop_table('wled_host')
    # ### end Alembic commands ###
